language: python
notifications:
  email: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
- USE_H5SERV=true 
- USE_H5SERV=false 
install:
- sudo apt-get update -qq
- sudo apt-get install -qq libhdf5-serial-dev
- pip uninstall numpy -y
- pip install numpy>=1.10.4
- pip install requests
- pip install pytz
- 'if [ "${USE_H5SERV}" = "true" ]; then
     pip install tornado ;
     pip install watchdog ;
     git clone https://github.com/HDFGroup/hdf5-json.git ;
     cd hdf5-json ;
     python setup.py install ;
     cd .. ;
     git clone https://github.com/HDFGroup/h5serv.git ;
   fi'
script:
- echo use_h5serv ${USE_H5SERV}
- 'if [ "${USE_H5SERV}" == "true" ]; then
    echo "setting up h5serv" ;
    cd h5serv/util/admin ;
    python makepwd_file.py ;
    python update_pwd.py -a -u test_user1 -p test ;
    python update_pwd.py -a -u test_user2 -p test ;
    cd ../.. ;
    python server/app.py >app.out & 
    sleep 5 ;
    cd .. ;
    export HS_ENDPOINT=http://127.0.0.1:5000 ;
    export H5PYD_TEST_FOLDER=h5pyd_test.hdfgroup.org ;
    export HS_PASSWORD=test ;
    export TEST2_PASSWORD=test ;
  else
    export HS_ENDPOINT=http://52.4.181.237:5104 ;
    export H5PYD_TEST_FOLDER=/home/test_user1/h5pyd_test/${TRAVIS_PYTHON_VERSION} ;
    curl ${HS_ENDPOINT}/about
  fi'
- python setup.py install
- echo endpoint ${HS_ENDPOINT}
- echo python_version ${TRAVIS_PYTHON_VERSION}
- echo test folder ${H5PYD_TEST_FOLDER}
- echo user ${HS_USERNAME}
- echo password ${HS_PASSWORD}
- echo test2_user ${TEST2_USERNAME}
- echo test2 password ${TEST2_PASSWORD}
- python testall.py
 